api_platform:
    # The title of the API.
    title: 'API Adab'
    # The description of the API.
    description: 'API Adab Platform'
    # The version of the API.
    version: '0.1.0'
    # Set this to false if you want Webby to disappear.
    show_webby: true
    elasticsearch:
        # To enable or disable Elasticsearch support.
        enabled: false

        # The hosts to the Elasticsearch nodes.
        hosts: ['ada.df']

        # The mapping between resource classes and indexes.
        mapping: []


    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    formats:
        jsonld:
            mime_types:
                - application/ld+json
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
        jsonhal:
            mime_types:
                - application/hal+json
