stages:
  - build
  - clean

########################
### PRODUCTION       ###
########################

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN
    - docker login --username $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
#  tags:
#    - adab

# Clean some shit
clean:
  stage: clean
  script:
    - echo docker images
#  tags:
#    - adab
