version: "3.8"

services:
  # Nginx proxy for api Adab
  nginx:
    container_name: adab_nginx
    image: nginx:latest
    depends_on:
      - api
    volumes:
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf    # nginx conf
      - ./data/nginx/logs:/var/log/nginx                          # logs
      - api_public:/app/public              # move uploads files from adab_api
    ports:
      - 8080:80

  # Adab api
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: adab_api_dev
    container_name: adab_api
    environment:
      APP_ENV: dev
      #      DATABASE_URL: mysql://root:root@mcontainer_name:ysql:3306/adab
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: adab
      DATABASE_USER: root
      DATABASE_PASS: root
      JWT_PASSPHRASE: 951429850sa
    volumes:
      - api_public:/app/public
      - ./data/api/logs:/app/var/log
      - ./config:/app/config  # for developing
      - ./src:/app/src
      - ./templates:/app/templates
    depends_on:
      - mysql

  # MySQL container
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  # Adminer for MySQL and MongoDB
  adminer:
    image: adminer
    container_name: adab_adminer_db
    restart: always
    ports:
      - 8081:8080  # port for adminer 8081

volumes:
  api_public:
