version: "3.8"

services:
  # Nginx for api Adab
  nginx:
    container_name: adab_nginx
    image: nginx:latest
    volumes:
      - ./public:/var/www/adab-api/public:ro
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    links:
      - api

  # Adab container
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: adab_api_dev
    container_name: adab_api
    links:
      - mysql
    volumes:
      - ./config:/var/www/adab-api/config
      - ./src:/var/www/adab-api/src
      - ./templates:/var/www/adab-api/templates
      - ./docker/php/php.ini-development:/usr/local/etc/php/conf.d/php.ini
    env_file:
      - ./.env.local

  # MySQL container
  mysql:
    image: mysql
    container_name: adab_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

#  # MongoDB container
#  mongo:
#    image: mongo
#    container_name: adab_mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    ports:
#      - 27017:27017

  # Adminer for MySQL and MongoDB
  adminer:
    image: adminer
    container_name: adab_adminer_db
    restart: always
    ports:
      - 8081:8080  # port for adminer 8081
