version: "3.8"

services:
  # Nginx for api Adab
  nginx:
    container_name: adab_nginx
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf/api.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/adab-api:cached
#      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8085:80
    links:
      - api

  # Adab container
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: adab_api_dev
    container_name: adab_api
    links:
      - db
    volumes:
      - ./:/var/www/adab-api:cached
      - ./docker/php/php.ini-development:/usr/local/etc/php/conf.d/php.ini
    env_file:
      - ./docker/backend.env

  # MySQL container
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: adab_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  # PostgreSQl container
#  db:
#    image: postgres
#    container_name: adab_postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: root
#    ports:
#      - 5432:5432
#
#  # MongoDB container
#  mongo:
#    image: mongo
#    container_name: adab_mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    ports:
#      - 27017:27017

  # Adminer for MySQL and MongoDB
  adminer:
    image: adminer
    container_name: adab_adminer_db
    restart: always
    ports:
      - 8086:8080  # port for adminer 8086
