version: "3.8"

services:
  # Nginx for api Adab
  nginx:
    container_name: adab_nginx
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf/api.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/adab-api
#      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8085:80
    links:
      - api

  # Adab container
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: adab_api_dev
    container_name: adab_api
    links:
      - mysql
#      - redis
    volumes:
      - ./:/var/www/adab-api
    env_file:
      - ./docker/backend.env

  # MySQL container
  mysql:
    image: mysql
    container_name: adab_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: adab
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

# Adminer for MySQL
  adminer:
    image: adminer
    restart: always
    ports:
      - 8086:8080  # port for adminer 8086
#
## Redis image
#  redis:
#    image: redis
#
# MySQL - DB Server
#volumes:
#  logvolume01: {}