api_login_check:
  path: /api/login_check

#register:
#  path: /register
#  controller: App\Controller\DefaultController::register
#  methods: POST
#
#api:
#  path: /api
#  controller: App\Controller\DefaultController::api
